=== GraysonRicketts/GraysonRicketts.github.io/.astro/collections/projects.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "url": {
      "type": "string"
    },
    "repoUrl": {
      "type": "string",
      "format": "uri"
    },
    "gif": {
      "type": "string"
    },
    "featured": {
      "default": false,
      "type": "boolean"
    },
    "order": {
      "default": 99,
      "type": "number"
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "title",
    "description",
    "url",
    "featured",
    "order"
  ],
  "additionalProperties": false
}

=== GraysonRicketts/GraysonRicketts.github.io/src/content/projects/dark-mode-extension.json
{
  "title": "Dark Mode Chrome Extension",
  "description": "A simple Chrome extension that adds dark mode functionality to any website.",
  "url": "https://github.com/GraysonRicketts/simple-dark-mode",
  "repoUrl": "https://github.com/GraysonRicketts/simple-dark-mode",
  "featured": true,
  "order": 2,
  "gif": "dark-mode.gif"
}

=== GraysonRicketts/GraysonRicketts.github.io/src/content/projects/headphone-battery-monitor.json
{
  "title": "Headphone Battery Monitor",
  "description": "A windows taskbar monitor to watch the battery level of your wireless headphones.",
  "url": "https://github.com/GraysonRicketts/headphone-battery-monitor",
  "repoUrl": "https://github.com/GraysonRicketts/headphone-battery-monitor",
  "featured": true,
  "order": 2,
  "gif": "headphone-battery-monitor.png"
}
